### PR TITLE
Feature/params

### PR DESCRIPTION
**Pull request by bezoerb**
This PR allows using all available twigjs params. It also allows a more lightweight way to define custom functions and filters.

### CODE REVIEW

**Comment by stefanullinger** [comment]
Hi @bezoerb, thanks for your great enhancements to this library! Do you think we should go for version 2.0.0 with this and remove the [_extensions_ option](https://github.com/stefanullinger/grunt-twig-render#optionsextensions)? Or should we keep both ways of defining extensions to Twig?

**Comment by bezoerb** [comment]
@stefanullinger please keep the extensions option as this is required to define [custom tags](https://github.com/twigjs/twig.js/wiki/Extending-twig.js-With-Custom-Tags).

**Comment by axten** [comment]
+1 for that PR!

**Comment by stefanullinger** [comment]
Published as v1.8.0 – https://github.com/stefanullinger/grunt-twig-render/releases/tag/v1.8.0.

**Comment by axten** [comment]
thanks!

**Pull request merged**
