### PR TITLE
update twigjs to version 1.10.4

### PR DESCRIPTION
**Pull request by axten**

### CODE REVIEW

**Comment by axten** [comment]
@stefanullinger can you merge this PR, please?

**Comment by stefanullinger** [comment]
The build is failing.

**Comment by axten** [comment]
ok I will have a look, sry for the disturbance!

**Comment by stefanullinger** [comment]
Maybe it will work, when we update the nodejs environment version in the travis.yml file?!

**Comment by axten** [comment]
maybe, go with node >= 4 seems to be a good turn

**Comment by stefanullinger** [comment]
Published in v1.8.1 – thank you!

**Comment by axten** [comment]
thank you too ;)

**Pull request merged**
